- name: Test if VM exists
  delegate_to: localhost
  shell: virsh list --all --name | grep "^{{ inventory_hostname }}$"

  failed_when: false
  changed_when: false

  register: vm_exists

- name: Create VM
  delegate_to: localhost
  command: 
    argv:
    - "{{ role_path }}/script/install.sh"
    - "{{ vm_source_image }}"
    - "{{ inventory_hostname }}"
    - "{{ vm_portgroup }}"
    - "{{ vm_ip_address }}"
    - "{{ vm_gateway_address }}"
  when: vm_exists.rc == 1
