- name: Test if VM exists
  delegate_to: localhost
  shell: virsh list --all --name | grep "^{{ inventory_hostname }}$"

  failed_when: false
  changed_when: false

  register: vm_exists

- name: Create VM
  delegate_to: localhost
  command: 
    cmd: >-
     {{ role_path }}/script/install.sh
     {{ vm_source_image }}
     {{ inventory_hostname }}
     {{ vm_portgroup }}
     {{ vm_ip_address }}
     {{ vm_gateway_address }}
     {{ vm_cpus if vm_cpus is defined else '' }}
     {{ vm_memory if vm_memory is defined else '' }}
     
  when: vm_exists.rc == 1
